### ISSUE TITLE
Failure building (docker-compose) `bad download` for `node-pre-gyp`

### ISSUE THREAD

**Issue by zeigerpuppy** [pojntfx/nextcloud-talk-bot-jitsi#1]
I am trying to build a docker container and getting the following error:

```
Step 4/8 : RUN apt install -y gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget protobuf-compiler
 ---> Using cache
 ---> a90ef6ab67d1
Step 5/8 : COPY . .
 ---> Using cache
 ---> 95d8cac56829
Step 6/8 : RUN npm ci
 ---> Running in c0d2381fbb9c

> grpc-tools@1.8.1 install /app/node_modules/grpc-tools
> node-pre-gyp install

node-pre-gyp WARN Using needle for node-pre-gyp https download
node-pre-gyp ERR! install error
node-pre-gyp ERR! stack Error: bad download
node-pre-gyp ERR! stack     at Unpack.afterTarball (/app/node_modules/grpc-tools/node_modules/node-pre-gyp/lib/install.js:100:46)
node-pre-gyp ERR! stack     at Unpack.emit (events.js:315:20)
node-pre-gyp ERR! stack     at Unpack.[maybeClose] (/app/node_modules/grpc-tools/node_modules/tar/lib/unpack.js:171:12)
node-pre-gyp ERR! stack     at Unpack.[unpend] (/app/node_modules/grpc-tools/node_modules/tar/lib/unpack.js:394:21)
node-pre-gyp ERR! stack     at /app/node_modules/grpc-tools/node_modules/tar/lib/unpack.js:308:46
node-pre-gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:163:23)
node-pre-gyp ERR! System Linux 4.19.24-20.container
node-pre-gyp ERR! command "/usr/local/bin/node" "/app/node_modules/grpc-tools/node_modules/.bin/node-pre-gyp" "install"
node-pre-gyp ERR! cwd /app/node_modules/grpc-tools
node-pre-gyp ERR! node -v v14.0.0
node-pre-gyp ERR! node-pre-gyp -v v0.12.0
node-pre-gyp ERR! not ok
bad download
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! grpc-tools@1.8.1 install: `node-pre-gyp install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the grpc-tools@1.8.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-04-25T04_25_19_745Z-debug.log
ERROR: Service 'nxtalkchatbots' failed to build: The command '/bin/sh -c npm ci' returned a non-zero code: 1
```

I am building from a freshly updated git clone of this repo.  My docker-compose file is as follows (some details changed for security).

```yaml
version: '3'

services:

     nxtalkproxyd:
        restart: always
        build:
            context: ../nextcloud-talk-bot-framework/
            dockerfile: Dockerfile
        container_name: nxtalkproxyd
        expose:
            - "1969"
        volumes:
            - nxtalkproxyd:/var/lib/nxtalkproxyd
        environment:
            NXTALKPROXYD_NXTALKPROXYD_DBPATH: "/var/lib/nxtalkproxyd"
            NXTALKPROXYD_NXTALKPROXYD_USERNAME: "jitsybot"
            NXTALKPROXYD_NXTALKPROXYD_PASSWORD: "PASSWORD"
            NXTALKPROXYD_NXTALKPROXYD_RADDR: "https://nextcloud.server.net"
        networks:
            docker2:
              ipv4_address: ${IP_nxtalkproxyd}

     nxtalkchatbots:
        container_name: nxtalkchatbots
        build:
            context: ../nextcloud-talk-bot-jitsi/
            dockerfile: Dockerfile
        restart: always
        environment:
            BOT_JITSI_ADDR: "jitsi.server.net"
            BOT_JITSI_BOT_NAME: "jitsibot"
            BOT_JITSI_SLEEP_TIME: 20
            BOT_NXTALKPROXYD_ADDR: "nxtalkproxyd:1969"
            BOT_JITSI_ROOM_PASSWORD_BYTE_LENGTH: 1
            BOT_COMMANDS: "#videochat,#videocall,#custom"
        networks:
            docker2:
              ipv4_address: ${IP_nxtalkchatbots}

# network
networks:
  docker2:
    external:
      name: docker2

volumes:
    nxtalkproxyd:
      driver: local
      driver_opts:
        type: 'none'
        device: '${PWD}/volumes/nxtalkproxyd'
        o: 'bind'
```

building from the image works, but I'd like to keep up to date with changes so am building from the Dockerfile.  My setup is a little unusual as I use kata-containers, but I don't think that's the cause of the build error.

**Comment by pojntfx** [comment]
@zeigerpuppy Sorry for taking so long to respond; I've been quite busy at uni these past few days. The error appears to be related to `node-gyp`; @rzerres is working on PR #3 right now, which does no longer rely on native grpc and should fix your issue.

**Comment by pojntfx** [comment]
@zeigerpuppy I've just merged PR #3 into master; the package does now no longer depend on node-gyp, so this should now fixed. Could you validate?

**Comment by zeigerpuppy** [comment]
@pojntfx Thanks for updating the dependencies.

The build with `docker-compose build --no-cache` is throwing an error at step 6, seems to be a different dependency issue:

```
Step 6/7 : RUN npm ci
 ---> Running in be4cbd7fb994
npm ERR! cipm can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
npm ERR!
npm ERR!
npm ERR! Missing: js-yaml@^3.13.1
npm ERR! Invalid: lock file's yargs@3.32.0 does not satisfy yargs@^15.3.1
npm ERR! Missing: @grpc/grpc-js@^1.0.3
npm ERR! Missing: @grpc/proto-loader@^0.5.4
npm ERR!

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-05-17T04_19_09_717Z-debug.log
ERROR: Service 'nxtalkchatbots' failed to build: The command '/bin/sh -c npm ci' returned a non-zero code: 1
```

**Comment by pojntfx** [comment]
@zeigerpuppy Sorry, my bad; I forgot to push the updated package-lock.json. `npm i` does not care, but `npm ci` does - see 22277edbb6c52a7a8b382cb4f9fe66b846f268d8.

**Comment by zeigerpuppy** [comment]
great, it is building now, but I note that there is an error thrown due to unknown arguments: `jitsiRoomPasswordByteLength`, `sleepTime`, `nxtalkproxydAddr`

```
nxtalkchatbots    | Unknown arguments: jitsiRoomPasswordByteLength, sleepTime, nxtalkproxydAddr
nxtalkchatbots    | npm ERR! code ELIFECYCLE
nxtalkchatbots    | npm ERR! errno 1
nxtalkchatbots    | npm ERR! @pojntfx/nextcloud-talk-bot-jitsi@1.0.1 start: `node main.js`
nxtalkchatbots    | npm ERR! Exit status 1
nxtalkchatbots    | npm ERR!
nxtalkchatbots    | npm ERR! Failed at the @pojntfx/nextcloud-talk-bot-jitsi@1.0.1 start script.
nxtalkchatbots    | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

in my docker-compose.yml, I am using the environment variables:

```yaml
        environment:
            NCTALKBOT_JITSI_ADDR: "jitsi.server.net"
            NCTALKBOT_BOT_NAME: "jitsibot"
            NCTALKBOT_SLEEP_TIME: 20
            NCTALKBOT_NXTALKPROXYD_ADDR: "nxtalkproxyd:1969"
            NCTALKBOT_JITSI_ROOM_PASSWORD_BYTE_LENGTH: 1
            NCTALKBOT_COMMANDS: "#videochat,#videocall,#custom"
```
